[workspace]
members = [
    "src/yblock",
    "src/ydriver"
]
resolver = "2"

[patch.crates-io]
tokenizers = { version = "0.19.1", path = "../tokenizers/tokenizers", default-features = false, features = ["unstable_wasm"] }
